import React, { useState } from 'react';
import { NoteSummary } from '../types';
import { SAMPLE_NOTE_INPUT, PRESET_NOTE_SUMMARY } from '../data/mockData';
import {
  FileText,
  Sparkles,
  Copy,
  Check,
  Download,
  FileCheck2,
  Bookmark,
  Share2,
  Clock,
  Layers,
  Sparkle,
} from 'lucide-react';

interface SmartNotesProps {
  theme: 'light' | 'dark';
}

export const SmartNotes: React.FC<SmartNotesProps> = ({ theme }) => {
  const [inputText, setInputText] = useState<string>(SAMPLE_NOTE_INPUT);
  const [isSummarizing, setIsSummarizing] = useState<boolean>(false);
  const [summaryData, setSummaryData] = useState<NoteSummary | null>(PRESET_NOTE_SUMMARY);
  const [copied, setCopied] = useState<boolean>(false);
  const [downloadSuccess, setDownloadSuccess] = useState<boolean>(false);

  const wordCount = inputText.trim() ? inputText.trim().split(/\s+/).length : 0;

  const handleSummarize = () => {
    if (!inputText.trim()) return;
    setIsSummarizing(true);

    setTimeout(() => {
      // Generate summary
      const lower = inputText.toLowerCase();
      let title = 'Study Notes Summary';
      let subject = 'Engineering Studies';

      if (lower.includes('machine learning') || lower.includes('data mining')) {
        title = 'Machine Learning Fundamentals & Industry Uses';
        subject = 'Machine Learning';
      } else if (lower.includes('python')) {
        title = 'Python Core Architecture & Data Structures';
        subject = 'Python';
      } else if (lower.includes('java')) {
        title = 'Java OOP & JVM Memory Execution';
        subject = 'Java';
      }

      setSummaryData({
        title,
        subject,
        originalWordCount: wordCount,
        summaryWordCount: Math.round(wordCount * 0.35),
        keyBulletPoints: [
          'Core concept: Systems acquire patterns iteratively from structured observations.',
          'Identifies statistical relationships to make predictive classifications.',
          'Key applications encompass recommendation systems, fraud detection, and autonomous devices.',
          'Accelerated by industry libraries like TensorFlow, PyTorch, and Scikit-learn.',
          'Data quality directly governs model accuracy and generalization capability.',
        ],
        keyTerms: [
          'Machine Learning',
          'Dataset',
          'Model Training',
          'Prediction',
          'Classification',
          'Neural Networks',
        ],
        examTips: [
          'Highlight difference between Supervised vs Unsupervised learning paradigms.',
          'Mention real-world recommendation engine as case study.',
        ],
      });

      setIsSummarizing(false);
    }, 1200);
  };

  const handleCopySummary = () => {
    if (!summaryData) return;
    const content = `${summaryData.title} (${summaryData.subject})\n\nKEY SUMMARY:\n${summaryData.keyBulletPoints
      .map((pt) => `• ${pt}`)
      .join('\n')}\n\nKEY TERMS:\n${summaryData.keyTerms.join(', ')}`;

    navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadNotes = () => {
    if (!summaryData) return;
    const textContent = `EDUGENIE AI STUDY NOTES
========================================
Title: ${summaryData.title}
Subject: ${summaryData.subject}
Original Words: ${summaryData.originalWordCount} -> Summary Words: ${summaryData.summaryWordCount}

AI SUMMARY:
${summaryData.keyBulletPoints.map((pt) => `- ${pt}`).join('\n')}

KEY TERMS TO REMEMBER:
${summaryData.keyTerms.map((term) => `* ${term}`).join('\n')}

EXAM QUICK TIPS:
${summaryData.examTips.map((tip) => `> ${tip}`).join('\n')}

Generated by EduGenie - Naan Mudhalvan Student Learning Prototype
`;

    const blob = new Blob([textContent], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `${summaryData.title.toLowerCase().replace(/\s+/g, '_')}_notes.md`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    setDownloadSuccess(true);
    setTimeout(() => setDownloadSuccess(false), 2500);
  };

  return (
    <div className="max-w-5xl mx-auto space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-slate-200 dark:border-slate-800">
        <div>
          <div className="flex items-center gap-2">
            <h1 className="text-2xl sm:text-3xl font-extrabold text-slate-900 dark:text-white">
              Smart Notes 📄
            </h1>
            <span className="text-[11px] font-semibold px-2 py-0.5 rounded bg-indigo-100 dark:bg-indigo-950 text-indigo-700 dark:text-indigo-300">
              AI Summarizer
            </span>
          </div>
          <p className="text-sm text-slate-600 dark:text-slate-400 mt-1">
            Convert lengthy study material into simple notes using AI.
          </p>
        </div>

        {/* Preset sample loader */}
        <button
          onClick={() => {
            setInputText(SAMPLE_NOTE_INPUT);
            setSummaryData(PRESET_NOTE_SUMMARY);
          }}
          className="px-3.5 py-1.5 rounded-lg border border-slate-200 dark:border-slate-700 text-xs font-semibold text-slate-600 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors self-start sm:self-auto flex items-center gap-1.5"
        >
          <Sparkle className="w-3.5 h-3.5 text-indigo-500" />
          <span>Load Sample Material</span>
        </button>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left Column: Input Material */}
        <div
          className={`lg:col-span-6 p-6 rounded-2xl border shadow-xs flex flex-col justify-between ${
            theme === 'dark' ? 'bg-slate-900 border-slate-800' : 'bg-white border-slate-200'
          }`}
        >
          <div className="space-y-3">
            <div className="flex items-center justify-between">
              <label className="text-xs font-bold text-slate-700 dark:text-slate-300 uppercase tracking-wider">
                Raw Study Material
              </label>
              <span className="text-xs text-slate-400 tabular-nums">{wordCount} words</span>
            </div>

            <textarea
              value={inputText}
              onChange={(e) => setInputText(e.target.value)}
              placeholder="Paste your study material here..."
              rows={13}
              className={`w-full p-4 rounded-xl border text-sm leading-relaxed focus:ring-2 focus:ring-indigo-500 focus:outline-none transition-all resize-none ${
                theme === 'dark'
                  ? 'bg-slate-800 border-slate-700 text-white placeholder-slate-400'
                  : 'bg-slate-50 border-slate-200 text-slate-900 placeholder-slate-400'
              }`}
            />
          </div>

          <div className="pt-4">
            <button
              onClick={handleSummarize}
              disabled={isSummarizing || !inputText.trim()}
              className="w-full py-3.5 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white font-bold text-sm shadow-md transition-all flex items-center justify-center gap-2 active:scale-95 disabled:opacity-50"
            >
              {isSummarizing ? (
                <>
                  <Sparkles className="w-4 h-4 animate-spin text-white" />
                  <span>EduGenie is analyzing and summarizing...</span>
                </>
              ) : (
                <>
                  <Sparkles className="w-4 h-4 text-white" />
                  <span>Summarize with AI</span>
                </>
              )}
            </button>
          </div>
        </div>

        {/* Right Column: AI Summary Output */}
        <div
          className={`lg:col-span-6 p-6 rounded-2xl border shadow-xs flex flex-col justify-between ${
            theme === 'dark' ? 'bg-slate-900 border-slate-800' : 'bg-white border-slate-200'
          }`}
        >
          {summaryData ? (
            <div className="space-y-5">
              {/* Summary Header */}
              <div className="border-b border-slate-100 dark:border-slate-800 pb-3 flex items-start justify-between gap-3">
                <div>
                  <div className="flex items-center gap-2">
                    <span className="text-[11px] font-bold uppercase tracking-wider text-indigo-600 dark:text-indigo-400">
                      AI Summary
                    </span>
                    <span className="text-slate-300 dark:text-slate-700">·</span>
                    <span className="text-xs text-slate-500">{summaryData.subject}</span>
                  </div>
                  <h3 className="text-base font-bold text-slate-900 dark:text-white mt-0.5">
                    {summaryData.title}
                  </h3>
                </div>

                <div className="text-right text-xs text-slate-500 dark:text-slate-400">
                  <span className="font-semibold text-emerald-600 dark:text-emerald-400">65%</span>{' '}
                  condensed
                </div>
              </div>

              {/* Bullet Points */}
              <div className="space-y-2.5">
                <h4 className="text-xs font-bold uppercase tracking-wider text-slate-700 dark:text-slate-300">
                  Key Concept Takeaways
                </h4>
                <ul className="space-y-2 text-sm text-slate-700 dark:text-slate-300 leading-relaxed">
                  {summaryData.keyBulletPoints.map((bullet, idx) => (
                    <li key={idx} className="flex items-start gap-2">
                      <span className="text-indigo-600 dark:text-indigo-400 font-bold shrink-0 mt-0.5">
                        •
                      </span>
                      <span>{bullet}</span>
                    </li>
                  ))}
                </ul>
              </div>

              {/* Key Terms */}
              <div className="space-y-2 pt-2 border-t border-slate-100 dark:border-slate-800">
                <h4 className="text-xs font-bold uppercase tracking-wider text-slate-700 dark:text-slate-300">
                  Key Terms
                </h4>
                <div className="flex flex-wrap gap-1.5">
                  {summaryData.keyTerms.map((term) => (
                    <span
                      key={term}
                      className="px-2.5 py-1 rounded-md text-xs font-medium bg-slate-100 dark:bg-slate-800 text-slate-800 dark:text-slate-200 border border-slate-200 dark:border-slate-700"
                    >
                      {term}
                    </span>
                  ))}
                </div>
              </div>

              {/* Action Buttons */}
              <div className="pt-4 border-t border-slate-100 dark:border-slate-800 flex flex-wrap items-center gap-3">
                <button
                  onClick={handleCopySummary}
                  className="flex-1 py-2.5 px-4 rounded-xl text-xs font-semibold border border-slate-200 dark:border-slate-700 text-slate-700 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-slate-800 transition-colors flex items-center justify-center gap-1.5"
                >
                  {copied ? (
                    <>
                      <Check className="w-3.5 h-3.5 text-emerald-500" />
                      <span className="text-emerald-600 font-bold">Summary Copied!</span>
                    </>
                  ) : (
                    <>
                      <Copy className="w-3.5 h-3.5 text-slate-500" />
                      <span>Copy Summary</span>
                    </>
                  )}
                </button>

                <button
                  onClick={handleDownloadNotes}
                  className="flex-1 py-2.5 px-4 rounded-xl text-xs font-semibold bg-indigo-600 hover:bg-indigo-700 text-white transition-all shadow-xs flex items-center justify-center gap-1.5 active:scale-95"
                >
                  {downloadSuccess ? (
                    <>
                      <FileCheck2 className="w-3.5 h-3.5 text-white" />
                      <span>Downloaded!</span>
                    </>
                  ) : (
                    <>
                      <Download className="w-3.5 h-3.5" />
                      <span>Download Notes</span>
                    </>
                  )}
                </button>
              </div>
            </div>
          ) : (
            <div className="h-full flex flex-col items-center justify-center text-center p-8 text-slate-400">
              <FileText className="w-12 h-12 stroke-[1.5] mb-2 opacity-50" />
              <p className="text-sm font-medium text-slate-600 dark:text-slate-300">
                No summary generated yet
              </p>
              <p className="text-xs text-slate-400 mt-1">
                Paste your lecture text or click "Load Sample Material" then click Summarize.
              </p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
